version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000' 
    depends_on:
      - sfcr_analyzer
    volumes:
      - ./backend:/backend 
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_SERVER=http://127.0.0.1:5000

  sfcr_analyzer:
    build: ./SFCR_Analyzer
    ports:
      - "5000:5000"
    volumes:
      - ./SFCR_Analyzer/input:/app/input
      - ./frontend:/frontend
      - ./SFCR_Analyzer/output:/app/output
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

