version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000' 
    depends_on:
      - sfcr_analyzer
    environment:
      - REACT_APP_SERVER=http://127.0.0.1:5000

  sfcr_analyzer:
    build: ./SFCR_Analyzer
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

